language: r
cache: packages

matrix:
  include:
    - os: linux
      sudo: required
      dist: precise
    - os: linux
      dist: trusty
      env: R_CODECOV=true
    - os: osx
      sudo: required
      osx_image: xcode8.3

r_github_packages:
  - jimhester/covr

warnings_are_errors: true

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
